---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Function to transform a Fasta file into a Tabular file
```{r}

FastaToTabular <- function (filename){
  
#read fasta file
  
    file1 <- readLines(filename)
    
#find the genename location by grepping >
    
  location <- which((str_sub(file1,1,1))==">")

#start an empty vector to collect name and sequence 

name=c()
sequence =c()



#number of genes= number of loops
#extract name first
for ( i in 1:length(location)){
  name_line = location[i]
  name1 = file1[name_line]
  name=c(name,name1)
#extract sequence between the names
#the last sequence will be missed using this strategy 
#so, we are using if condition to extract last sequence 
  start= location[i]+1
  end = location[i+1]-1
  if ( i < length (location)){
  
  end=end

  } else {
   
    end=length(file1)
  }
  
  lines = start:end
  sequence1= as.character(paste(file1[lines],collapse = ""))
  sequence =c(sequence,sequence1)
}

#now create table using name and sequence vector 

data <- tibble(name,sequence)



#finally export the file 
#before that remove preexisting file
#unlink(c("dna_table.csv"),force=TRUE)
#write.csv(data,"dna_table.csv")

#function ends
}
```

# Reading all .ffn files from prokka output
```{r}

files <- list.files(pattern=".ffn", recursive = T)

for(i in 1:length(files)) {
  dat <- FastaToTabular(files[i]) %>% 
    write.csv(file = paste0(files[i],".csv"))
}

```

# Function to transform Tablular files into Fasta files
```{r}
TabularToFasta <- function (filename){
  file <- read.csv (file=filename, header=TRUE)
  
  file = as.data.frame(file)
  #delete if any existing file 
  
  unlink(c("PROKKA_data_nucl_gyrA.fasta"), force=TRUE)
  
  #give output filename
  
  sink("PROKKA_data_nucl_gyrA.fasta")
  
  for (i in 1:nrow(file)){
    name = paste0(">",file[i,1])
    sequence = paste(file[i,2])
   cat(name,sep="\n")
   cat(sequence,sep="\n")
  }
  
#this is sink all the console output to the file 
  sink()
  
}

#usage 
#TabularToFasta("gene.csv")

```

# Extracting all ORFs that has "syrase subunit A" it its name
```{r}
files <- list.files(pattern=".csv", recursive = T)

PROKKA.data=c()
for(i in 1:length(files)) {
  dat <- read_csv(files[i])  
  colnames(dat) <- c("Number", "Name", "Sequence")

dat1 <- dat %>% 
  filter(grepl('gyrase subunit A', Name)) %>% 
  mutate(filename=files[i])
  
PROKKA.data <- rbind(PROKKA.data,dat1)
}

PROKKA.data.1 <- PROKKA.data %>% 
  mutate(filename = as.character(unlist(substr(filename, 0, nchar(filename)-15)))) %>% 
  mutate(Name = as.character(unlist(substr(Name, 3, nchar(Name)-0)))) %>%  
  subset(select = -c(Number)) %>% 
  unite(Name, c(filename, Name))

write_csv(PROKKA.data.1,"PROKKA_data_nucl_gyrA.csv")

TabularToFasta("PROKKA_data_nucl_gyrA.csv")
```



